apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Kafka cluster from developer-quickstart
  - https://github.com/streamshub/developer-quickstart//components/core/stack/kafka?ref=main
  # Console from developer-quickstart
  - https://github.com/streamshub/developer-quickstart//components/core/stack/streamshub-console?ref=main
  # Topics
  - ../../../components/topics
  # Apicurio Registry
  - ../../../components/apicurio-registry
  # Secrets
  - console-oidc-secret.yaml
  # Authorino instance + AuthConfig
  - authorino-cr.yaml
  - authconfig.yaml

patches:
  - path: kafka-oauth-patch.yaml
  - path: console-oauth-patch.yaml
