apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apicurio-registry
  namespace: kafka
  annotations:
    cert-manager.io/cluster-issuer: nip-io-ca-issuer
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - apicurio-registry.127.0.0.1.nip.io
      secretName: apicurio-registry-tls
  rules:
    - host: apicurio-registry.127.0.0.1.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: apicurio-registry
                port:
                  number: 8443
